import type { Business } from '@/types/business';

export const MOCK_FEATURED_PROVIDERS: Business[] = [
  {
    _id: 'mock-1',
    owner: 'mock-owner-1',
    email: 'rizwan@example.com',
    phone: '+923001234561',
    whatsapp: '+923001234561',
    name: 'Muhammad Rizwan',
    title: 'AC Repair & Installation Specialist',
    category: 'AC Repair',
    city: 'Islamabad',
    area: 'G-11',
    about: 'Professional AC technician with 8+ years of experience in repairing, installing, and servicing all types of air conditioners.',
    services: ['AC Repair', 'AC Installation', 'Gas Charging'],
    experience: 8,
    completedProjects: 240,
    specializations: ['Inverter AC', 'Split AC'],
    serviceAreas: ['Islamabad', 'Rawalpindi'],
    pricing: {
      calloutFee: '500',
      hourlyRate: '1000',
      minCharge: '800'
    },
    availability: 'Available',
    responseTime: '15 mins',
    socialLinks: { facebook: '', instagram: '', youtube: '', website: '', linkedin: '', tiktok: '' },
    profileImage: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=150',
    bannerImage: '',
    status: 'active',
    rating: 4.9,
    reviewsCount: 38,
    verification: true,
    featured: true,
    viewCount: 120,
    weeklyViews: 15,
    monthlyViews: 65,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'mock-2',
    owner: 'mock-owner-2',
    email: 'yasir@example.com',
    phone: '+923001234562',
    whatsapp: '+923001234562',
    name: 'Yasir Khan',
    title: 'Professional Electrician & Wiring Expert',
    category: 'Electrician',
    city: 'Islamabad',
    area: 'F-8',
    about: 'Expert electrician specializing in home wiring, short circuit repairs, UPS installation, and appliance maintenance.',
    services: ['Home Wiring', 'UPS Repair', 'Breaker Fixing'],
    experience: 5,
    completedProjects: 150,
    specializations: ['Home Automation', 'Industrial Wiring'],
    serviceAreas: ['Islamabad'],
    pricing: {
      calloutFee: '0',
      hourlyRate: '800',
      minCharge: '500'
    },
    availability: 'Available',
    responseTime: '30 mins',
    socialLinks: { facebook: '', instagram: '', youtube: '', website: '', linkedin: '', tiktok: '' },
    profileImage: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=150',
    bannerImage: '',
    status: 'active',
    rating: 4.8,
    reviewsCount: 26,
    verification: true,
    featured: true,
    viewCount: 95,
    weeklyViews: 10,
    monthlyViews: 40,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    _id: 'mock-3',
    owner: 'mock-owner-3',
    email: 'sajid@example.com',
    phone: '+923001234563',
    whatsapp: '+923001234563',
    name: 'Sajid Mehmood',
    title: 'Master Plumber & Leakage Fixer',
    category: 'Plumber',
    city: 'Islamabad',
    area: 'I-9',
    about: '20+ years of plumbing experience. Leakage detection, pipe fittings, geyser installation, and bathroom renovations.',
    services: ['Leakage Repair', 'Geyser Install', 'Drain Unclogging'],
    experience: 12,
    completedProjects: 450,
    specializations: ['Leakage Detection', 'Modern Bathroom Fit-outs'],
    serviceAreas: ['Islamabad', 'Rawalpindi'],
    pricing: {
      calloutFee: '400',
      hourlyRate: '1200',
      minCharge: '700'
    },
    availability: 'Available',
    responseTime: '20 mins',
    socialLinks: { facebook: '', instagram: '', youtube: '', website: '', linkedin: '', tiktok: '' },
    profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    bannerImage: '',
    status: 'active',
    rating: 4.7,
    reviewsCount: 54,
    verification: true,
    featured: true,
    viewCount: 180,
    weeklyViews: 25,
    monthlyViews: 90,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];
